Repository pykale/pykale, pull requests merged in 2021-12, with the labels that each got.

#271 Fix doc build, improve docstrings and MPCA pipeline fit efficiency
  docs/README.md
  docs/requirements.txt
  docs/source/kale.utils.rst
  kale/loaddata/multi_domain.py
  kale/pipeline/domain_adapter.py
  kale/pipeline/mpca_trainer.py
  kale/pipeline/multi_domain_adapter.py
  kale/pipeline/video_domain_adapter.py
Labels: documentation, enhancement

#272 Update progress_bar for PL 1.5.5 & change 'target' abbreviation
  examples/action_dann_lightn/README.md
  examples/action_dann_lightn/config.py
  examples/action_dann_lightn/configs/EPIC-D12D2-CDAN.yaml
  examples/action_dann_lightn/configs/EPIC-D12D2-DAN.yaml
  examples/action_dann_lightn/configs/EPIC-D12D2-DANN.yaml
  examples/action_dann_lightn/main.py
  examples/action_dann_lightn/model.py
  examples/action_dann_lightn/test.py
  examples/bindingdb_deepdta/main.py
  examples/digits_dann_lightn/README.md
  examples/digits_dann_lightn/config.py
  examples/digits_dann_lightn/configs/tutorial.yaml
  examples/digits_dann_lightn/main.py
  examples/digits_dann_lightn/tutorial.ipynb
  examples/multisource_adapt/README.md
  examples/multisource_adapt/main.py
  kale/loaddata/video_access.py
  kale/pipeline/domain_adapter.py
  kale/pipeline/multi_domain_adapter.py
  kale/pipeline/video_domain_adapter.py
  kale/predict/losses.py
  tests/loaddata/test_video_access.py
  tests/pipeline/test_domain_adapter.py
  tests/pipeline/test_video_domain_adapter.py
Labels: enhancement, minor

#273 add topk & multitask topk accuracies
  examples/action_dann_lightn/model.py
  kale/embed/video_feature_extractor.py
  kale/embed/video_i3d.py
  kale/embed/video_res3d.py
  kale/embed/video_se_i3d.py
  kale/embed/video_se_res3d.py
  kale/embed/video_selayer.py
  kale/loaddata/video_access.py
  kale/loaddata/video_multi_domain.py
  kale/pipeline/video_domain_adapter.py
  kale/predict/class_domain_nets.py
  kale/predict/losses.py
  kale/utils/download.py
  tests/predict/test_losses.py
Labels: documentation, tests, new feature

#282 Clarify when to request review and prefer just one label
  .github/pull_request_template.md
Labels: documentation
