Repository pykale/pykale, pull requests merged in 2021-07, with the labels that each got.

#174 Fix button links in tutorial
  examples/digits_dann_lightn/assets/binder.svg
  examples/digits_dann_lightn/tutorial.ipynb
Labels: documentation

#178 Reduce tests for video, fix video load, & remove binder icon
  examples/digits_dann_lightn/assets/binder.svg
  kale/loaddata/video_datasets.py
  setup.py
  tests/embed/test_video_feature_extractor.py
  tests/loaddata/test_video_access.py
Labels: tests

#187 Add dependabot
  .github/dependabot.yml
Labels: dependencies
