Repository pykale/pykale, pull requests merged in 2021-11, with the labels that each got.

#254 Fix bugs for upgrading PyTroch-lightning to 1.5
  kale/pipeline/domain_adapter.py
Labels: bug

#257 Update all files affected by PyTorch 1.10 and Torchvision 0.11.1
  kale/embed/video_res3d.py
  kale/embed/video_se_i3d.py
  kale/embed/video_se_res3d.py
Labels: bug, enhancement

#259 Raise an issue if tests fail.
  .github/ISSUE_TEMPLATE/action-fail.md
  .github/workflows/test.yml
Labels: work-in-progress, tests
