Repository pykale/pykale, pull requests merged in 2021-02, with the labels that each got.

#49 Set up mypy and add draft PR & US English guideline
  .pre-commit-config.yaml
  CONTRIBUTING.md
  docs/source/kale.embed.rst
  docs/source/kale.pipeline.rst
  kale/embed/linformer.py
  kale/embed/positional_encoding.py
  kale/loaddata/multi_domain.py
  kale/loaddata/video_datasets.py
  kale/loaddata/videos.py
  kale/pipeline/video_transformer.py
  setup.cfg
Labels: enhancement, work-in-progress

#50 Update dependencies, setup, and README (installation etc)
  .github/pull_request_template.md
  .github/workflows/build.yml
  .github/workflows/check.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  requirements.txt
  setup.py
Labels: dependencies

#53 Add DAN to digits_dann_lightn
  examples/digits_dann_lightn/configs/MN2UP-DAN.yaml
  examples/digits_dann_lightn/model.py
  kale/loaddata/multi_domain.py
Labels: bug, enhancement

#55 Proposal for README description change
  README.md
Labels: documentation

#58 Fix docs & add docs CI
  .github/pull_request_template.md
  .github/workflows/docs.yml
  CONTRIBUTING.md
  docs/requirements.txt
  docs/source/index.rst
  docs/source/kale.rst
  docs/source/modules.rst
  setup.py
Labels: documentation, enhancement

#51 MPCA udpate
  kale/embed/__init__.py
  kale/embed/mpca.py
Labels: enhancement, refactor

#60 Auto release and update setup
  .conda/bld.bat
  .conda/build.sh
  .conda/meta.yaml
  .github/pull_request_template.md
  .github/workflows/release.yml
  README.md
  setup.py
Labels: enhancement

#59 DeepDTA for drug-target interaction
  CONTRIBUTING.md
  docs/source/kale.embed.rst
  docs/source/kale.loaddata.rst
  docs/source/kale.pipeline.rst
  docs/source/kale.predict.rst
  docs/source/kale.prepdata.rst
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/__init__.py
  examples/bindingdb_deepdta/config.py
  examples/bindingdb_deepdta/configs/IC50-DeepDTA.yaml
  examples/bindingdb_deepdta/configs/Kd-DeepDTA.yaml
  examples/bindingdb_deepdta/configs/Ki-DeepDTA.yaml
  examples/bindingdb_deepdta/figures/bindingdb.jpg
  examples/bindingdb_deepdta/figures/deepdta.png
  examples/bindingdb_deepdta/main.py
  examples/bindingdb_deepdta/model.py
  kale/embed/seq_nn.py
  kale/loaddata/tdc_datasets.py
  kale/pipeline/deep_dti.py
  kale/predict/decode.py
  kale/prepdata/chem_transform.py
Labels: work-in-progress

#57 Test strategy
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  CONTRIBUTING.md
  README.md
  setup.py
  tests/embed/__init__.py
  tests/embed/test_attention_cnn.py
  tests/embed/test_gcn.py
  tests/embed/test_gripnet.py
  tests/embed/test_image_cnn.py
  tests/embed/test_init.py
  tests/embed/test_mpca.py
  tests/embed/test_positional_encoding.py
  tests/embed/test_video_i3d.py
  tests/embed/test_video_res3d.py
  tests/loaddata/__init__.py
  tests/loaddata/test_cifar_access.py
  tests/loaddata/test_dataset_access.py
  tests/loaddata/test_digits_access.py
  tests/loaddata/test_init.py
  tests/loaddata/test_mnistm.py
  tests/loaddata/test_multi_domain.py
  tests/loaddata/test_sampler.py
  tests/loaddata/test_usps.py
  tests/loaddata/test_video_access.py
  tests/loaddata/test_video_datasets.py
  tests/loaddata/test_videos.py
  tests/pipeline/__init__.py
  tests/pipeline/test_domain_adapter.py
  tests/pipeline/test_init.py
  tests/predict/__init__.py
  tests/predict/test_class_domain_nets.py
  tests/predict/test_init.py
  tests/predict/test_isonet.py
  tests/predict/test_losses.py
  tests/prepdata/test_image_transform.py
  tests/prepdata/test_init.py
  tests/prepdata/test_prep_cmr.py
  tests/prepdata/test_tensor_reshape.py
  tests/prepdata/test_video_transform.py
  tests/regression/.gitkeep
  tests/regression/__init__.py
  tests/test_data/empty.csv
  tests/utils/__init__.py
  tests/utils/test_csv_logger.py
  tests/utils/test_init.py
  tests/utils/test_logger.py
  tests/utils/test_print.py
  tests/utils/test_seed.py
Labels: work-in-progress
