Repository pykale/pykale, pull requests merged in 2021-06, with the labels that each got.

#151 Add Class subsampling
  kale/loaddata/dataset_access.py
  kale/loaddata/multi_domain.py
  kale/loaddata/video_multi_domain.py
  tests/loaddata/test_digits_access.py
  tests/loaddata/test_video_access.py
Labels: new feature, work-in-progress

#152 link to mybinder / colab
  docs/source/index.rst
Labels: documentation, work-in-progress

#149 Digits notebook
  .gitignore
  examples/digits_dann_lightn/config.py
  examples/digits_dann_lightn/configs/MN2UP-CDAN.yaml
  examples/digits_dann_lightn/configs/MN2UP-DAN.yaml
  examples/digits_dann_lightn/configs/MN2UP-DANN.yaml
  examples/digits_dann_lightn/configs/tutorial.yaml
  examples/digits_dann_lightn/main.py
  examples/digits_dann_lightn/tutorial.ipynb
  requirements.txt
  setup.py
Labels: work-in-progress

#154 fix links for colab
  docs/source/index.rst
  docs/source/tutorial.md
  examples/digits_dann_lightn/tutorial.ipynb
Labels: bug

#155 Update docs for next release & restore MNIST
  README.md
  docs/source/introduction.md
  docs/source/tutorial.md
  tests/loaddata/test_digits_access.py
Labels: documentation, tests

#156 Empty tests and remove MNIST test
  tests/embed/__init__.py
  tests/embed/test_gcn.py
  tests/embed/test_init.py
  tests/embed/test_positional_encoding.py
  tests/embed/test_video_res3d.py
  tests/loaddata/__init__.py
  tests/loaddata/test_dataset_access.py
  tests/loaddata/test_digits_access.py
  tests/loaddata/test_init.py
  tests/loaddata/test_mnistm.py
  tests/loaddata/test_multi_domain.py
  tests/loaddata/test_sampler.py
  tests/loaddata/test_usps.py
  tests/loaddata/test_video_datasets.py
  tests/loaddata/test_videos.py
  tests/pipeline/__init__.py
  tests/pipeline/test_init.py
  tests/predict/__init__.py
  tests/predict/test_init.py
  tests/predict/test_losses.py
  tests/prepdata/test_init.py
  tests/prepdata/test_tensor_reshape.py
  tests/prepdata/test_video_transform.py
  tests/regression/.gitkeep
  tests/regression/__init__.py
  tests/utils/__init__.py
  tests/utils/test_init.py
Labels: tests

#157 Add concord_index calculation into DeepDTA
  kale/evaluate/metrics.py
  kale/pipeline/deep_dti.py
  tests/pipeline/test_deep_dti.py
Labels: enhancement, tests

#159 Add interpret module
  docs/source/index.rst
  docs/source/kale.interpret.rst
  docs/source/kale.loaddata.rst
  docs/source/kale.pipeline.rst
  docs/source/kale.prepdata.rst
  kale/interpret/model_weights.py
  tests/pipeline/test_mpca_trainer.py
Labels: new feature, tests

#160 Update docs w.r.t. CIKM submission
  README.md
  docs/source/tutorial.md
Labels: documentation
