Repository pykale/pykale, pull requests merged in 2021-08, with the labels that each got.

#196 Add Google Drive Download API
  examples/video_loading/main.py
  kale/utils/download.py
  tests/utils/test_download.py
Labels: new feature, tests

#189 Create test_sampler.py and update doc for tests
  tests/README.md
  tests/loaddata/test_sampler.py
Labels: tests

#200 nightly test run
  .github/workflows/test.yml
Labels: tests

#201 No "extras", only "normal" or "dev" installs
  .github/ISSUE_TEMPLATE/bug-report.md
  docs/source/installation.md
  requirements.txt
  setup.py
Labels: enhancement

#165 Notebook tutorial for the bindingdb_deepdta example
  .gitignore
  docs/source/index.rst
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/config.py
  examples/bindingdb_deepdta/configs/tutorial.yaml
  examples/bindingdb_deepdta/tutorial.ipynb
Labels: documentation, work-in-progress

#199 CMR PAH notebook example
  docs/source/kale.interpret.rst
  docs/source/kale.loaddata.rst
  examples/cmri_mpca/CMR_PAH.ipynb
  examples/cmri_mpca/README.md
  examples/cmri_mpca/__init__.py
  examples/cmri_mpca/config.py
  examples/cmri_mpca/configs/tutorial_lr.yaml
  examples/cmri_mpca/configs/tutorial_svc.yaml
  examples/cmri_mpca/main.py
  examples/cmri_mpca/tutorial.ipynb
  examples/drug_gripnet/README.md
  examples/drug_gripnet/config.py
  kale/interpret/model_weights.py
  kale/interpret/visualize.py
  kale/loaddata/get_dicom.py
  kale/pipeline/mpca_trainer.py
  kale/prepdata/image_transform.py
  kale/utils/download.py
  setup.py
  tests/pipeline/test_mpca_trainer.py
  tests/prepdata/test_image_transform.py
  tests/utils/test_download.py
Labels: enhancement, refactor, tests

#206 cmr tutorial.ipynp colab link to main branch
  examples/cmri_mpca/tutorial.ipynb
Labels: enhancement
