Repository pykale/pykale, pull requests merged in 2021-04, with the labels that each got.

#90 Test mpca
  tests/embed/test_mpca.py
Labels: tests

#91 MPCA pipeline
  .github/pull_request_template.md
  docs/source/kale.pipeline.rst
  kale/pipeline/mpca_trainer.py
  tests/pipeline/test_mpca_trainer.py
Labels: enhancement, tests

#94 Update test guidelines
  tests/readme.md
Labels: documentation

#95 Update readme
  README.md
  docs/images/pykale_logo.png
Labels: documentation

#97 Add changelog CI and update logo
  .github/CHANGELOG.md
  .github/changelog-ci-config.json
  .github/workflows/changelog.yml
  README.md
  docs/images/pykale_logo.png
Labels: enhancement

#104 Test CNNTransformer
  tests/embed/test_attention_cnn.py
Labels: tests

#106 Update the readmes of docs, examples, and tests
  docs/README.md
  examples/README.md
  tests/readme.md
Labels: documentation

#101 Keep __init__ simple without public and private interfaces
  kale/embed/__init__.py
  kale/evaluate/__init__.py
  kale/interpret/__init__.py
Labels: enhancement

#107 only ci test multiple python versions on linux
  .github/workflows/test.yml
Labels: tests

#113 Update reference to pykale master to pykale main
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  docs/source/index.rst
  tests/readme.md
Labels: refactor

#108 Remove Development Status in meta info
  setup.py
Labels: documentation

#115 Fix tests readme link
  .github/CONTRIBUTING.md
  tests/README.md
Labels: documentation

#121 Update new logos
  README.md
  docs/images/pykale_logo.png
  docs/images/pykale_logo_long.png
Labels: enhancement

#122 Test deep_dta
  .github/workflows/test.yml
  tests/embed/test_seq_nn.py
  tests/loaddata/test_digits_access.py
  tests/loaddata/test_tdc_datasets.py
  tests/pipeline/test_deep_dti.py
  tests/predict/test_decode.py
  tests/prepdata/test_chem_transform.py
Labels: tests

#123 Merge prep_cmr with image_transform plus tests
  docs/source/kale.prepdata.rst
  kale/prepdata/image_transform.py
  kale/prepdata/prep_cmr.py
  tests/prepdata/test_image_transform.py
  tests/prepdata/test_prep_cmr.py
Labels: refactor, tests

#92 Update Action DA Pipeline
  .gitignore
  docs/source/kale.embed.rst
  docs/source/kale.loaddata.rst
  docs/source/kale.pipeline.rst
  examples/action_dann_lightn/README.md
  examples/action_dann_lightn/config.py
  examples/action_dann_lightn/configs/EPIC-D12D2-DAN.yaml
  examples/action_dann_lightn/main.py
  examples/action_dann_lightn/model.py
  examples/action_dann_lightn/test.py
  examples/digits_dann_lightn/main.py
  kale/embed/video_feature_extractor.py
  kale/embed/video_i3d.py
  kale/embed/video_res3d.py
  kale/embed/video_se_i3d.py
  kale/embed/video_se_res3d.py
  kale/embed/video_selayer.py
  kale/loaddata/action_multi_domain.py
  kale/loaddata/multi_domain.py
  kale/loaddata/sampler.py
  kale/loaddata/video_access.py
  kale/loaddata/video_datasets.py
  kale/loaddata/videos.py
  kale/pipeline/action_domain_adapter.py
  kale/pipeline/domain_adapter.py
  kale/predict/class_domain_nets.py
  kale/prepdata/video_transform.py
  kale/utils/csv_logger.py
  kale/utils/seed.py
Labels: enhancement

#120 Update PR for changelog, cherry pick, and test re-run tip
  .github/CONTRIBUTING.md
  README.md
  docs/source/index.rst
  docs/source/installation.md
  docs/source/tutorial.md
Labels: documentation

#132 Create download.py
  docs/source/kale.utils.rst
  examples/action_dann_lightn/model.py
  kale/embed/video_feature_extractor.py
  kale/embed/video_i3d.py
  kale/embed/video_res3d.py
  kale/embed/video_se_i3d.py
  kale/embed/video_se_res3d.py
  kale/embed/video_selayer.py
  kale/loaddata/action_multi_domain.py
  kale/loaddata/video_access.py
  kale/pipeline/action_domain_adapter.py
  kale/predict/class_domain_nets.py
  kale/utils/download.py
  tests/utils/test_download.py
Labels: enhancement

#127 Add video_access test
  tests/loaddata/test_video_access.py
Labels: tests
