Repository pykale/pykale, pull requests merged in 2021-03, with the labels that each got.

#67 Add DeepDTA architecture in README and fix some issues in code
  docs/source/index.rst
  docs/source/kale.evaluate.rst
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/config.py
  examples/bindingdb_deepdta/configs/IC50-DeepDTA.yaml
  examples/bindingdb_deepdta/main.py
  examples/bindingdb_deepdta/model.py
  kale/evaluate/metrics.py
  kale/pipeline/deep_dti.py
Labels: bug, documentation

#69 Move test doc
  CONTRIBUTING.md
  tests/readme.md
Labels: documentation

#66 MPCA switch to svd solver
  kale/embed/__init__.py
  kale/embed/mpca.py
  setup.py
Labels: enhancement

#74 Minor restructure and update to the root and examples
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  examples/README.md
  examples/data/README.md
Labels: enhancement

#76 Test mpca
  tests/embed/test_mpca.py
  tests/test_data/gait_gallery_data.mat
  tests/test_data/mpca_baseline_res.mat
Labels: enhancement, help wanted

#80 Extend automated test matrix and rename lint
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
Labels: bug

#82 Remove requirements in examples and update setup
  examples/action_dann_lightn/requirements.txt
  examples/bindingdb_deepdta/README.md
  examples/cifar_cnntransformer/requirements.txt
  examples/cifar_isonet/requirements.txt
  examples/digits_dann_lightn/requirements.txt
  examples/video_loading/requirements.txt
  setup.py
Labels: dependencies

#81 Docs update version and installation
  README.md
  docs/requirements.txt
  docs/source/conf.py
  docs/source/index.rst
  docs/source/installation.md
  docs/source/modules.rst
  setup.py
Labels: documentation

#70 Add tests for utils.print
  tests/context.py
  tests/utils/test_print.py
Labels: work-in-progress

#84 Auto assign to the default project
  .github/CONTRIBUTING.md
  .github/pull_request_template.md
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/project.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: enhancement
