Repository pykale/pykale, pull requests merged in 2022-01, with the labels that each got.

#285 Landmark uncertainty readme
  examples/landmark_uncertainty/README.md
  examples/landmark_uncertainty/__init__.py
  examples/landmark_uncertainty/figures/quantile_binning.png
Labels: new feature

#283 "val" in variable names to "valid"
  docs/source/yaml.md
  examples/action_dann_lightn/main.py
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/main.py
  examples/bindingdb_deepdta/tutorial.ipynb
  examples/cifar_cnntransformer/main.py
  examples/cifar_cnntransformer/trainer.py
  examples/cifar_isonet/main.py
  examples/cifar_isonet/trainer.py
  examples/digits_dann_lightn/config.py
  examples/digits_dann_lightn/configs/tutorial.yaml
  examples/digits_dann_lightn/main.py
  examples/digits_dann_lightn/tutorial.ipynb
  examples/drug_gripnet/main.py
  examples/drug_gripnet/trainer.py
  examples/multisource_adapt/main.py
  kale/loaddata/dataset_access.py
  kale/loaddata/image_access.py
  kale/loaddata/multi_domain.py
  kale/loaddata/video_access.py
  kale/loaddata/video_multi_domain.py
  kale/pipeline/deep_dti.py
  kale/pipeline/domain_adapter.py
  kale/pipeline/multi_domain_adapter.py
  kale/pipeline/video_domain_adapter.py
  tests/loaddata/test_image_access.py
  tests/loaddata/test_video_access.py
  tests/pipeline/test_deep_dti.py
  tests/pipeline/test_video_domain_adapter.py
Labels: refactor

#289 update readme to say functional code is on another branch,
  examples/landmark_uncertainty/README.md
Labels: documentation, minor
