Repository pykale/pykale, pull requests merged in 2022-10, with the labels that each got.

#353 Fix importlib-metadata
  .github/workflows/changelog.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pre-commit.yml
  .github/workflows/project.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
Labels: dependencies

#348 Create stale workflow
  .github/workflows/stale.yml
Labels: new feature

#346 Update the polypharmacy example and GripNet implementation
  examples/polypharmacy_gripnet/README.md
  examples/polypharmacy_gripnet/config.py
  examples/polypharmacy_gripnet/configs/PoSE_MINI-GripNet.yaml
  examples/polypharmacy_gripnet/main.py
  examples/polypharmacy_gripnet/model.py
  examples/polypharmacy_gripnet/trainer.py
  examples/polypharmacy_gripnet/utils.py
  kale/embed/gripnet.py
  kale/evaluate/metrics.py
  kale/loaddata/polypharmacy_datasets.py
  kale/predict/decode.py
  kale/prepdata/graph_negative_sampling.py
  tests/embed/test_gripnet.py
Labels: enhancement
