Repository pykale/pykale, pull requests merged in 2022-08, with the labels that each got.

#246 Add MIDA, CoIRLS, distribution plot, and brain example
  .github/workflows/test.yml
  .gitignore
  docs/requirements.txt
  docs/source/kale.embed.rst
  examples/autism_detection/__init__.py
  examples/autism_detection/config.py
  examples/autism_detection/configs/tutorial.yaml
  examples/autism_detection/tutorial.ipynb
  examples/toy_domain_adaptation/__init__.py
  examples/toy_domain_adaptation/main.py
  examples/toy_domain_adaptation/tutorial.ipynb
  examples/video_loading/README.md
  kale/embed/factorization.py
  kale/interpret/model_weights.py
  kale/interpret/visualize.py
  kale/pipeline/mpca_trainer.py
  kale/pipeline/multi_domain_adapter.py
  setup.py
  tests/embed/test_factorization.py
  tests/embed/test_gripnet.py
  tests/pipeline/test_deep_dti.py
  tests/pipeline/test_multi_domain_adapter.py
Labels: new feature

#329 update colab links in notebook examples
  examples/autism_detection/tutorial.ipynb
  examples/digits_dann_lightn/tutorial.ipynb
  examples/toy_domain_adaptation/tutorial.ipynb
Labels: bug

#331 update cmr example landmark visualization
  examples/cmri_mpca/tutorial.ipynb
Labels: enhancement

#330 Fix problems of tests for Python version 3.7, 3.8 and 3.9
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  docs/source/installation.md
  examples/autism_detection/tutorial.ipynb
  examples/bindingdb_deepdta/main.py
  examples/bindingdb_deepdta/tutorial.ipynb
  examples/digits_dann_lightn/tutorial.ipynb
  examples/toy_domain_adaptation/tutorial.ipynb
  examples/video_loading/README.md
  kale/utils/print.py
  pyproject.toml
  setup.py
  tests/utils/test_print.py
Labels: dependencies

#333 Update docs and readme for 0.1.0 release
  README.md
  docs/source/notebooks.md
  examples/README.md
Labels: documentation

#337 Update GripNet example and contributing guidelines
  .github/CONTRIBUTING.md
  docs/source/index.rst
  examples/cmri_mpca/README.md
  examples/drug_gripnet/README.md
  examples/polypharmacy_gripnet/README.md
  examples/polypharmacy_gripnet/__init__.py
  examples/polypharmacy_gripnet/config.py
  examples/polypharmacy_gripnet/configs/PoSE_MINI-GripNet.yaml
  examples/polypharmacy_gripnet/main.py
  examples/polypharmacy_gripnet/model.py
  examples/polypharmacy_gripnet/trainer.py
  examples/polypharmacy_gripnet/utils.py
Labels: documentation

#339 Add setup options and improve docs
  README.md
  docs/source/installation.md
  setup.py
  tests/README.md
Labels: dependencies

#340 Update reading DICOM and marker visualization
  .zenodo.json
  README.md
  examples/autism_detection/README.md
  examples/autism_detection/tutorial.ipynb
  examples/cmri_mpca/README.md
  examples/cmri_mpca/config.py
  examples/cmri_mpca/configs/tutorial_lr.yaml
  examples/cmri_mpca/configs/tutorial_svc.yaml
  examples/cmri_mpca/main.py
  examples/cmri_mpca/tutorial.ipynb
  examples/toy_domain_adaptation/README.md
  kale/interpret/visualize.py
  kale/loaddata/image_access.py
  kale/loaddata/mnistm.py
  tests/prepdata/test_image_transform.py
Labels: new feature

#338 Improve GripNet implementation
  docs/source/installation.md
  docs/source/kale.prepdata.rst
  kale/embed/gripnet.py
  kale/prepdata/supergraph_construct.py
  setup.py
  tests/embed/test_gripnet.py
Labels: new feature

#341 Update Colab installation, add notebook hook, correct deepdta, and improve docs
  .pre-commit-config.yaml
  README.md
  docs/source/installation.md
  docs/source/kale.pipeline.rst
  docs/source/notebooks.md
  examples/autism_detection/tutorial.ipynb
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/figures/deepdta.png
  examples/bindingdb_deepdta/model.py
  examples/bindingdb_deepdta/tutorial.ipynb
  examples/cmri_mpca/tutorial.ipynb
  examples/digits_dann_lightn/tutorial.ipynb
  examples/toy_domain_adaptation/tutorial.ipynb
  kale/pipeline/deepdta.py
  setup.py
  tests/pipeline/test_deepdta.py
Labels: refactor

#342 Add arguments to visualize, rename examples, and update docs
  .pre-commit-config.yaml
  README.md
  docs/README.md
  docs/source/index.rst
  docs/source/notebooks.md
  docs/source/tutorial.md
  docs/source/yaml.md
  examples/README.md
  examples/action_dann/README.md
  examples/action_dann/__init__.py
  examples/action_dann/config.py
  examples/action_dann/configs/EPIC-D12D2-CDAN.yaml
  examples/action_dann/configs/EPIC-D12D2-DAN.yaml
  examples/action_dann/configs/EPIC-D12D2-DANN.yaml
  examples/action_dann/main.py
  examples/action_dann/model.py
  examples/action_dann/test.py
  examples/cmri_mpca/config.py
  examples/cmri_mpca/main.py
  examples/cmri_mpca/tutorial.ipynb
  examples/digits_dann/README.md
  examples/digits_dann/__init__.py
  examples/digits_dann/config.py
  examples/digits_dann/configs/MN2UP-CDAN.yaml
  examples/digits_dann/configs/MN2UP-DAN.yaml
  examples/digits_dann/configs/MN2UP-DANN.yaml
  examples/digits_dann/configs/tutorial.yaml
  examples/digits_dann/main.py
  examples/digits_dann/model.py
  examples/digits_dann/tutorial.ipynb
  examples/landmark_uncertainty_qbin/README.md
  examples/landmark_uncertainty_qbin/__init__.py
  examples/landmark_uncertainty_qbin/figures/quantile_binning.png
  examples/multisite_neuroimg_adapt/README.md
  examples/multisite_neuroimg_adapt/__init__.py
  examples/multisite_neuroimg_adapt/config.py
  examples/multisite_neuroimg_adapt/configs/tutorial.yaml
  examples/multisite_neuroimg_adapt/tutorial.ipynb
  examples/multisource_adapt/README.md
  examples/office_multisource_adapt/README.md
  examples/office_multisource_adapt/__init__.py
  examples/office_multisource_adapt/config.py
  examples/office_multisource_adapt/configs/Office2A-M3SDA.yaml
  examples/office_multisource_adapt/configs/Office2A-MFSAN.yaml
  examples/office_multisource_adapt/configs/digits-M3SDA.yaml
  examples/office_multisource_adapt/configs/tutorial.yaml
  examples/office_multisource_adapt/main.py
  examples/office_multisource_adapt/model.py
  kale/interpret/visualize.py
  kale/pipeline/multi_domain_adapter.py
  tests/prepdata/test_image_transform.py
Labels: enhancement

#343 Add missing comma to bibtex and clarify python version supported
  README.md
  docs/source/installation.md
  examples/video_loading/README.md
  setup.py
Labels: documentation
