Repository pykale/pykale, pull requests merged in 2023-05, with the labels that each got.

#356 Update CIFAR CNNTransformer example to Lightning
  .github/ISSUE_TEMPLATE/bug-report.md
  .pre-commit-config.yaml
  docs/source/kale.pipeline.rst
  examples/action_dann/model.py
  examples/cifar_cnntransformer/CIFAR10-ModelComparison-ValAcc-Lightning.png
  examples/cifar_cnntransformer/README.md
  examples/cifar_cnntransformer/config.py
  examples/cifar_cnntransformer/configs/CF10-CNNTransformer-huge.yaml
  examples/cifar_cnntransformer/configs/CF10-CNNTransformer-large.yaml
  examples/cifar_cnntransformer/configs/CF10-CNNTransformer-small.yaml
  examples/cifar_cnntransformer/configs/CF10-CNNTransformer.yaml
  examples/cifar_cnntransformer/configs/CF10-StandardCNN-huge.yaml
  examples/cifar_cnntransformer/configs/CF10-StandardCNN.yaml
  examples/cifar_cnntransformer/main.py
  examples/cifar_cnntransformer/model.py
  examples/cifar_cnntransformer/trainer.py
  kale/embed/attention_cnn.py
  kale/embed/image_cnn.py
  kale/loaddata/image_access.py
  kale/loaddata/video_access.py
  kale/pipeline/base_nn_trainer.py
  kale/pipeline/domain_adapter.py
  kale/predict/class_domain_nets.py
  kale/predict/losses.py
  tests/embed/test_image_cnn.py
  tests/pipeline/test_base_nn_trainer.py
  tests/predict/test_class_domain_nets.py
Labels: new feature

#370 Support py3.10 and remove py3.7
  .github/workflows/pre-commit.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  setup.py
Labels: bug

#377 Remove the py3.7 and added py3.10 in docs & switch to pip install rdkit & replace np.float with np.float64.
  .github/workflows/test.yml
  README.md
  docs/requirements.txt
  docs/source/installation.md
  examples/bindingdb_deepdta/README.md
  examples/bindingdb_deepdta/tutorial.ipynb
  examples/video_loading/README.md
  kale/embed/factorization.py
  kale/loaddata/sampler.py
  pyproject.toml
Labels: work-in-progress

#380 Fix readthedoc error
  docs/requirements.txt
Labels: bug

#358 Add option to log messages to terminal
  kale/utils/logger.py
  tests/utils/test_logger.py
Labels: new feature

#382 Fix "OSError" error in testflow
  examples/bindingdb_deepdta/tutorial.ipynb
Labels: bug
