Repository pykale/pykale, pull requests merged in 2025-04, with the labels that each got.

#459 Upgrade minimum sklearn version from 0.23.2 to 1.6.1
  setup.py
Labels: dependencies

#460 Update cross-validation for transductive domain adaptation
  kale/evaluate/cross_validation.py
  tests/embed/__init__.py
  tests/embed/test_factorization.py
  tests/evaluate/test_cross_validation.py
  tests/helpers/toy_dataset.py
Labels: new feature

#461 Add codecov token for testing
  .github/workflows/test.yml
Labels: tests
