Repository pykale/pykale, pull requests merged in 2025-05, with the labels that each got.

#437 Add mida_trainer pipeline
  docs/source/kale.pipeline.rst
  examples/cmri_mpca/tutorial.ipynb
  kale/embed/factorization.py
  kale/evaluate/cross_validation.py
  kale/pipeline/mida_trainer.py
  tests/embed/test_factorization.py
  tests/evaluate/test_cross_validation.py
  tests/pipeline/__init__.py
  tests/pipeline/test_mida_trainer.py
Labels: new feature

#463 Add symmetric weights and connectome vizualization
  kale/interpret/model_weights.py
  kale/interpret/visualize.py
  tests/interpret/test_model_weights.py
  tests/interpret/test_visualize.py
Labels: new feature

#464 Implement AutoMIDAClassificationTrainer and MIDA enhancement
  kale/embed/factorization.py
  kale/pipeline/mida_trainer.py
  tests/embed/test_factorization.py
  tests/pipeline/test_mida_trainer.py
Labels: enhancement, new feature

#469 refactor DomainNetSmallImage
  kale/predict/class_domain_nets.py
  tests/predict/test_class_domain_nets.py
Labels: refactor
