Repository pykale/pykale, pull requests merged in 2025-06, with the labels that each got.

#470 Improve code test coverage
  kale/embed/feature_fusion.py
  tests/embed/test_feature_fusion.py
  tests/loaddata/test_image_access.py
  tests/loaddata/test_multiomics_datasets.py
  tests/loaddata/test_polypharmacy_datasets.py
Labels: tests

#474 Add landscape and grants
  README.md
Labels: documentation

#471 Add multimodal tri-stream pre-training and fine-tuning for image and signal modalities
  docs/requirements.txt
  docs/source/kale.embed.rst
  docs/source/kale.loaddata.rst
  docs/source/kale.pipeline.rst
  docs/source/kale.prepdata.rst
  kale/embed/feature_fusion.py
  kale/embed/image_cnn.py
  kale/embed/multimodal_encoder.py
  kale/embed/signal_cnn.py
  kale/evaluate/metrics.py
  kale/loaddata/image_access.py
  kale/loaddata/signal_access.py
  kale/loaddata/signal_image_access.py
  kale/pipeline/multimodal_trainer.py
  kale/predict/decode.py
  kale/prepdata/image_transform.py
  kale/prepdata/signal_transform.py
  setup.py
  tests/embed/test_feature_fusion.py
  tests/embed/test_image_cnn.py
  tests/embed/test_multimodal_encoder.py
  tests/embed/test_signal_cnn.py
  tests/evaluate/test_metrics.py
  tests/loaddata/test_image_access.py
  tests/loaddata/test_signal_access.py
  tests/loaddata/test_signal_image_access.py
  tests/pipeline/test_multimodal_trainer.py
  tests/predict/test_decode.py
  tests/prepdata/test_image_transform.py
  tests/prepdata/test_signal_transform.py
Labels: tests, new feature

#438 Upgrade to support Numpy 2.0.0+
  .github/workflows/test.yml
  examples/bindingdb_deepdta/tutorial.ipynb
  examples/cifar_isonet/config.py
  examples/digits_dann/config.py
  examples/digits_dann/tutorial.ipynb
  examples/office_multisource_adapt/config.py
  examples/office_multisource_adapt/configs/tutorial.yaml
  examples/toy_domain_adaptation/tutorial.ipynb
  examples/video_loading/main.py
  kale/loaddata/avmnist_datasets.py
  kale/loaddata/multi_domain.py
  kale/loaddata/sampler.py
  kale/loaddata/video_multi_domain.py
  kale/pipeline/domain_adapter.py
  kale/prepdata/string_transform.py
  pyproject.toml
  setup.py
  tests/loaddata/test_image_access.py
  tests/loaddata/test_sampler.py
  tests/pipeline/test_domain_adapter.py
  tests/pipeline/test_video_domain_adapter.py
Labels: refactor

#472 Fix auto-unwrapping in the multiomics example.
  kale/pipeline/multiomics_trainer.py
Labels: bug
